- examples/crossterm.rs
- examples/profiler.rs
- src/view.rs
- src/view/conditional_view.rs
- src/view/empty_view.rs
- src/view/modifier.rs
- src/view/modifier/fixed_frame.rs
- src/view/modifier/flex_frame.rs
- tests/conditional_view.rs
- tests/fixed_frame.rs
- tests/flex_frame.rs
- tests/padding.rs
.frame and .flex_frame that mirror the SwiftUI functionality
ConditionalView to allow if / else
EmptyView
> Adds frame modifiers and conditional

- Cargo.lock
- Cargo.toml
- examples/crossterm.rs
- examples/profiler.rs
- src/view/foreach.rs
- src/view/hstack.rs
- src/view/vstack.rs
- tests/foreach.rs
- tests/hstack.rs
- tests/spacer.rs
- tests/vstack.rs
Adds configurable alignment to ForEach
renames some stack builder functions to with_
just gonna ignore semver here...there is still a message in the readme
> ForEach alignment, naming

- README.md
Updates readme to reflect latest status
> v0.3 Documentation

- Cargo.lock
- Cargo.toml
- src/render/animate.rs
- src/render/conditional_tree.rs
- src/render/rounded_rect.rs
Update Cargo.toml, it's perfectly usable how it is, lets see how long until I need breaking changes...😭
> Version 0.3.0

- .github/workflows/book.yml
> Publish Book on main

- README.md
- docs/book/src/quickstart.md
- rust-toolchain.toml
- src/lib.rs
Turns out I deleted the code that originally required nightly. Awesome.
> Nightly not required anymore

- .github/workflows/rust.yml
- docs/book/book.toml
- docs/book/src/SUMMARY.md
- docs/book/src/introduction.md
- docs/book/src/quickstart.md
- Adds tests to book, and gets examples passing
- Adds introduction chapter
> Book updates

- Cargo.lock
- Cargo.toml
- README.md
- docs/book/src/building-views/alignment.md
- docs/book/src/building-views/mixed-alignment.md
- docs/book/src/building-views/separating-views.md
- docs/book/src/building-views/stack-spacing.md
- docs/book/src/building-views/stacks.md
- docs/book/src/quickstart.md
- docs/book/src/quickstart.rs
- examples/crossterm.rs
- examples/espresso.rs
- src/render.rs
- src/render/empty.rs
- src/view.rs
- tests/animation.rs
- tests/hstack.rs
- tests/match_view.rs
Creates a trait to alias the super verbose `impl Renderable<Rgb565, Renderables: EmbeddedGraphicsRender<Rgb565>>`
> More convenient view alias

- src/view/foreach.rs
- tests/foreach.rs
- Fix spacing bug not applying spacing to exact-sized foreach views.
- Add docs
- Replace the dumb IntoIterator bound with a slice
> Foreach refactor

- docs/book/src/building-views.md
- docs/book/src/building-views/stacks.md
> Doc tweaks

- src/view.rs
- src/view/modifier.rs
- src/view/modifier/background.rs
- tests/background.rs
Allows rendering background content inside the bounds of a foreground layout
> Background view

- Cargo.lock
- Cargo.toml
- docs/book/src/building-views.md
- docs/book/src/quickstart.md
> Version 0.4

- docs/book/src/building-views/conditional-views.md
> Small typo in book

- Cargo.lock
- Cargo.toml
- examples/espresso.rs
- src/animation.rs
- src/lib.rs
- src/render/animate.rs
- src/view.rs
- src/view/modifier/animated.rs
- tests/animation.rs
Adds animation curves.
> [!WARNING]
> Includes a breaking change around animation, I don't think anyone is seriously using this crate with animation and 0.4.0 just got published....if it _was_ a problem and you're looking at this PR, please leave a comment.
> Animation curves

- .github/workflows/rust.yml
Adds semver check, renames jobs for consistency
> Check semver in CI

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/view.rs
- src/view/modifier.rs
- src/view/modifier/hidden.rs
- tests/hidden.rs
Adds an occasionally useful modifier to use a view for layout, but not render it.
> Hidden modifier

- src/layout.rs
- src/view.rs
- src/view/modifier/background.rs
- tests/background.rs
- tests/hidden.rs
Adds required alignment to background, breaking change.
> Background Alignment

- docs/book/src/animation/transitions.md
- src/primitives/dimension.rs
- src/render.rs
- src/render/one_of.rs
- src/view.rs
- src/view/divider.rs
- src/view/match_view.rs
- src/view/shape/capsule.rs
- src/view/shape/circle.rs
- src/view/shape/rectangle.rs
- src/view/shape/rounded_rectangle.rs
- src/view/view_that_fits.rs
- tests/flex_frame.rs
- tests/view_that_fits.rs
Adds a view that picks the best fitting option along a given axis. 
This is typically useful when font sizes are dynamic or a view is presented in multiple contexts / screen sizes
> View that fits

- .github/FUNDING.yml
> Funding file

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- buoyant-examples/battery/Cargo.toml
- buoyant-examples/battery/src/app.rs
- buoyant-examples/battery/src/bin/simulator.rs
- buoyant-examples/battery/src/charge_simulator.rs
- buoyant-examples/battery/src/color.rs
- buoyant-examples/battery/src/lib.rs
- buoyant-examples/battery/src/state.rs
- buoyant-examples/battery/src/view.rs
- buoyant-examples/battery/src/view/charge.rs
- buoyant-examples/battery/src/view/screen_setting.rs
- buoyant-examples/battery/src/view/stats.rs
Adds an example that simulates a portable battery display.
Adds workspace properties to the main package
> Battery example

- .github/workflows/rust.yml
- buoyant-examples/battery/src/app.rs
- src/view/modifier/geometry_group.rs
- src/view/modifier/priority.rs
Adds checks for unapplied rustfmt fixes
> Add rustfmt check

- .github/workflows/rust.yml
Reports code coverage to codecov.io
> Codecov reporting

- src/render/capsule.rs
- src/render/circle.rs
- src/render/collections.rs
- src/render/image.rs
- src/render/offset.rs
- src/render/rect.rs
- src/render/rounded_rect.rs
- src/render/shade_subtree.rs
- src/render/text.rs
New tests for animated join functionality.
New tests for collection rendering order.
> Render tests

- Cargo.lock
- Cargo.toml
- docs/book/src/animation/animated-render-loops.md
- docs/book/src/animation/compound-animation.md
- docs/book/src/animation/render-trees.md
- docs/book/src/animation/transitions.md
- docs/book/src/building-views/alignment.md
- docs/book/src/building-views/collections.md
- docs/book/src/building-views/conditional-views.md
- docs/book/src/building-views/fonts.md
- docs/book/src/building-views/manual-view-lifecycle.md
- docs/book/src/building-views/mixed-alignment.md
- docs/book/src/building-views/separating-views.md
- docs/book/src/building-views/stack-spacing.md
- docs/book/src/building-views/stacks.md
- docs/book/src/quickstart.md
- scripts/test-book.sh
- src/view.rs
Adds a prelude to view, and updates docs to use it.
> View prelude

- src/render.rs
- src/render/option.rs
> Option renderable

- src/view.rs
- src/view/geometry_reader.rs
- tests/common/helpers.rs
- tests/common/mod.rs
- tests/geometry_reader.rs
- tests/mod.rs
- tests/scroll_view/animated_drop.rs
- tests/scroll_view/constrained_movement.rs
- tests/scroll_view/embedded_button.rs
- tests/scroll_view/mod.rs
- tests/scroll_view/snapping.rs
Adds a GeometryReader view to create views that require knowledge of a layout size
> GeometryReader

- .github/workflows/book.yml
Check for alpha or beta in the version, skip publishing if it's present
> Skip book publishing for prerelease versions

- buoyant-examples/battery/src/view/charge.rs
- buoyant-examples/battery/src/view/screen_setting.rs
- docs/book/src/SUMMARY.md
- docs/book/src/animation/transitions.md
- docs/book/src/interactivity.md
- docs/book/src/interactivity/event-loops.md
- examples/espresso.rs
- src/view/modifier.rs
- src/view/shape/rounded_rectangle.rs
Updates transition book docs now that it's implemented.
Adds (the start of) some docs for interactivity.
Updates code examples that can use `background_color(color, in_shape)` to use it.
> Doc updates
